# -*- mode: ruby -*-
# vi: set ft=ruby :

VAGRANTFILE_API_VERSION = "2"

$platform = ENV["TEST_OS"]

Vagrant.configure(VAGRANTFILE_API_VERSION) do |cluster|
  
  cluster.vm.box = if $platform == "UBUNTU"
    "bento/ubuntu-14.04"
  elsif $platform == "CENTOS"
    "bento/centos-6.7"
  elsif $platform == "DEBIAN"
    "bento/debian-7.4"
  else
    "bento/ubuntu-14.04"
  end

  cluster.vm.define "example" do |machine|
      machine.vm.hostname = "binarytemple.java"
      #machine.vm.network "private_network", ip: "10.42.0.6"

      machine.vm.provision "ansible" do |ansible|
        ansible.playbook = "./example.yml"
        ansible.verbose = "vvvv"
        ansible.limit = "all"
      end
  end
end
